# Generated by Django 4.2.27 on 2026-02-12 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='tenant',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'TENANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tenant_flat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('society', 'flat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancebill',
            unique_together={('flat', 'month', 'year')},
        ),
    ]
